-- =============================================================================
-- DADOS INICIAIS DO CARDÁPIO (demo)
-- Rode DEPOIS do schema.sql. Pode editar tudo depois pelo painel /admin.
-- 📸 As fotos são placeholders do Unsplash: troque pelas fotos reais do cliente
--    pelo painel (upload vai direto para o Supabase Storage).
-- =============================================================================

insert into public.menu_items
  (category, name, description, ingredients, price, image_url, available, sort_order, badge)
values
  ('smash', 'Smash Ouro',
   'Duas bolinhas de blend Angus prensadas na chapa a 250°C até formar aquela crosta caramelizada e crocante. Queijo cheddar inglês derretendo nas bordas e o nosso molho da casa no brioche selado na manteiga.',
   array['2x smash Angus 80g', 'Cheddar inglês', 'Cebola na chapa', 'Picles da casa', 'Molho Ouro', 'Brioche artesanal'],
   38.90, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd', true, 1, 'Mais pedido'),
  ('smash', 'Triple Smash',
   'Para quem não negocia: três camadas de smash com crosta de Maillard, triplo cheddar e bacon de barriga suína defumado em lenha frutífera. Suculento do começo ao último guardanapo.',
   array['3x smash Angus 80g', 'Triplo cheddar', 'Bacon defumado artesanal', 'Molho Ouro', 'Brioche artesanal'],
   49.90, 'https://images.unsplash.com/photo-1606131731446-5568d87113aa', true, 2, null),
  ('smash', 'Smash Clássico',
   'O essencial bem feito: um smash de 100g na chapa bem quente, queijo prato derretido, alface americana crocante, tomate e maionese caseira de alho assado.',
   array['Smash Angus 100g', 'Queijo prato', 'Alface americana', 'Tomate', 'Maionese de alho assado', 'Brioche artesanal'],
   29.90, 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90', true, 3, null),
  ('smash', 'Smash Inferno',
   'Duplo smash com pepper jack, jalapeños em conserva feita aqui, cebola crispy e maionese de chipotle defumado. Ardência na medida, sem perder o sabor da carne.',
   array['2x smash Angus 80g', 'Pepper jack', 'Jalapeño da casa', 'Cebola crispy', 'Maionese de chipotle', 'Brioche artesanal'],
   41.90, 'https://images.unsplash.com/photo-1553979459-d2229ba7433b', true, 4, 'Picante'),
  ('signature', 'Ouro Negro Trufado',
   'Blend exclusivo de 180g com costela e acém Angus maturados 21 dias, grelhado no ponto que você pedir. Queijo brie derretido, cogumelos salteados na manteiga e molho de trufa negra artesanal.',
   array['Blend maturado 21 dias 180g', 'Brie', 'Cogumelos paris e shimeji', 'Molho de trufa negra', 'Rúcula', 'Brioche preto'],
   64.90, 'https://images.unsplash.com/photo-1550547660-d9450f859349', true, 1, 'Assinatura'),
  ('signature', 'Costela 12h',
   'Costela bovina defumada por 12 horas em lenha de macieira, desfiada e prensada sobre blend de 160g. Finalizada com queijo coalho maçaricado e barbecue de rapadura feito na casa.',
   array['Blend Angus 160g', 'Costela defumada 12h', 'Queijo coalho maçaricado', 'Barbecue de rapadura', 'Cebola roxa', 'Brioche artesanal'],
   59.90, 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5', true, 2, null),
  ('signature', 'Gorgonzola & Mel',
   'O contraste que vicia: blend de 180g, gorgonzola cremoso, cebola caramelizada lentamente no vinho do Porto, nozes tostadas e um fio de mel de laranjeira.',
   array['Blend Angus 180g', 'Gorgonzola', 'Cebola caramelizada no Porto', 'Nozes tostadas', 'Mel de laranjeira', 'Brioche artesanal'],
   57.90, 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9', true, 3, null),
  ('signature', 'Bacon Jam Royale',
   'Blend de 180g com crosta de pimenta-do-reino, geleia de bacon cozida por 4 horas com café e açúcar mascavo, cheddar maturado e ovo de gema mole.',
   array['Blend Angus 180g', 'Geleia de bacon com café', 'Cheddar maturado', 'Ovo de gema mole', 'Brioche artesanal'],
   61.90, 'https://images.unsplash.com/photo-1596662951482-0c4ba74a6df6', true, 4, null),
  ('signature', 'Garden Gold',
   'Burger de grão-de-bico, cogumelos e beterraba assada com casquinha dourada, queijo muçarela de búfala, tomate confit e pesto de manjericão. Vegetariano, sem abrir mão de sabor.',
   array['Burger vegetal da casa 150g', 'Muçarela de búfala', 'Tomate confit', 'Pesto de manjericão', 'Folhas', 'Brioche artesanal'],
   46.90, 'https://images.unsplash.com/photo-1571091718767-18b5b1457add', true, 5, 'Veggie'),
  ('sides', 'Fritas Rústicas',
   'Batatas cortadas à mão, cozidas e fritas duas vezes para ficarem crocantes por fora e cremosas por dentro. Sal de parrilla e alecrim.',
   array['Batata asterix', 'Sal de parrilla', 'Alecrim', 'Maionese da casa'],
   22.90, 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877', true, 1, null),
  ('sides', 'Fritas Trufadas',
   'Nossas fritas rústicas finalizadas com azeite de trufa branca, parmesão ralado na hora e salsinha fresca.',
   array['Batata asterix', 'Azeite de trufa branca', 'Parmesão', 'Salsinha'],
   32.90, 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d', true, 2, 'Imperdível'),
  ('sides', 'Onion Rings na Cerveja',
   'Anéis de cebola empanados em massa de cerveja artesanal e panko, fritos na hora. Acompanha molho barbecue de rapadura.',
   array['Cebola doce', 'Massa de cerveja', 'Panko', 'Barbecue de rapadura'],
   26.90, 'https://images.unsplash.com/photo-1639024471283-03518883512d', true, 3, null),
  ('sides', 'Cheddar & Bacon Fries',
   'Fritas rústicas cobertas com creme de cheddar inglês e farofa de bacon defumado crocante.',
   array['Batata asterix', 'Creme de cheddar', 'Farofa de bacon', 'Cebolinha'],
   34.90, 'https://images.unsplash.com/photo-1585109649139-366815a0d713', true, 4, null),
  ('drinks', 'Refrigerante Lata',
   'Coca-Cola, Coca Zero, Guaraná Antarctica ou Sprite. Informe o sabor na observação.',
   array['350ml'],
   7.90, 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97', true, 1, null),
  ('drinks', 'Limonada Siciliana',
   'Limão-siciliano espremido na hora, hortelã fresca e um toque de gengibre. Feita no pedido.',
   array['500ml', 'Limão-siciliano', 'Hortelã', 'Gengibre'],
   16.90, 'https://images.unsplash.com/photo-1621263764928-df1444c5e859', true, 2, null),
  ('drinks', 'Milkshake Doce de Leite',
   'Sorvete artesanal de creme batido com doce de leite argentino e calda de caramelo salgado. Cremoso de verdade.',
   array['400ml', 'Sorvete de creme artesanal', 'Doce de leite argentino', 'Caramelo salgado'],
   24.90, 'https://images.unsplash.com/photo-1572490122747-3968b75cc699', true, 3, null),
  ('drinks', 'Cerveja Artesanal IPA',
   'IPA de cervejaria local, amargor marcante e notas cítricas — harmoniza perfeitamente com os signature.',
   array['473ml', 'Venda proibida para menores de 18 anos'],
   22.90, 'https://images.unsplash.com/photo-1535958636474-b021ee887b13', false, 4, null),
  ('desserts', 'Brownie com Flor de Sal',
   'Brownie de chocolate 70% cacau, casquinha crocante e centro úmido, finalizado com flor de sal e calda quente de chocolate.',
   array['Chocolate 70%', 'Flor de sal', 'Calda de chocolate'],
   21.90, 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c', true, 1, null),
  ('desserts', 'Cheesecake de Frutas Vermelhas',
   'Cheesecake cremoso assado lentamente sobre base de biscoito amanteigado, com calda de frutas vermelhas feita na casa.',
   array['Cream cheese', 'Biscoito amanteigado', 'Calda de frutas vermelhas'],
   23.90, 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad', true, 2, null);

